sudo: false
language: python
python:
  - "2.7"
install:
  - "cd server"
  - "python setup.py install"
  - "pip install -r dev-requirements.txt"
  - "cd .."
  - "cp config.yml.sample config.yml"
  - "python ./bin/migrations/init_db.py"
  - "(cd client && npm run build)"
# command to run tests
script:
  - "ludobox start &" # lauch a ludobox server in the background
  - "ludobox test"
  - "killall ludobox" # kill all processes at the end
